apiVersion: skaffold/v4beta13
kind: Config

metadata:
  name: cicada

requires:
  - path: shared/infrastructure/nats
  - path: service/chat

profiles:
  - name: local
    activation:
      - kubeContext: microk8s
