apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: chat-server

requires:
  - path: deployments/infrastructure/valkey

build:
  local:
    push: true
  artifacts:
    - image: tesserical/cicada-chat-server
      bazel:
        target: //service/chat:grpc_server.tar

# TODO: Uncomment once the helm chart is ready
#deploy:
#  helm:
#    releases:
#      - name: chat-server
#        chartPath: deployments/helm
#        namespace: cicada
#        createNamespace: true
#        setValueTemplates:
#          image.repository : "{{.IMAGE_NAME_tesserical_cicada_chat_server}}"
#          image.tag : "{{.IMAGE_TAG_tesserical_cicada_chat_server}}"
##          migrations.image.registry: "{{.IMAGE_DOMAIN_tesserical_finance_ledger_postgres_migrations}}"
##          migrations.image.repository : "{{.IMAGE_REPO_NO_DOMAIN_tesserical_finance_ledger_postgres_migrations}}"
##          migrations.image.tag : "{{.IMAGE_TAG_tesserical_finance_ledger_postgres_migrations}}@{{.IMAGE_DIGEST_tesserical_finance_ledger_postgres_migrations}}"
#        valuesFiles: []

profiles:
  - name: local
#    Uncomment this if extra deploy manifests are needed
#    manifests:
#      rawYaml:
#        - "deployments/env/local/extras/*"
#    deploy:
#      kubectl: {}
# TODO: Uncomment once the helm chart is ready
#    patches:
#      - op: add
#        path: /deploy/helm/releases/0/valuesFiles
#        value:
#          - deployments/env/local/values.yaml